name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dateutil pytest mock pytest-cov coverage ruff

      - name: Check code formatting
        run: ruff format .

      - name: Check for code errors
        run: ruff check .

      - name: Run Test
        run: |
          py.test --cov coveralls --cov-report term-missing --cov-report=lcov --cov=resources tests/

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
